-- MySQL Script generated by MySQL Workbench
-- jeu. 19 nov. 2020 19:35:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`poison`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`poison` ;

CREATE TABLE IF NOT EXISTS `mydb`.`poison` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `image` VARCHAR(100) NULL,
  `antidote` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`symptom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`symptom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`symptom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingredient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `image` VARCHAR(100) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`poison_has_symptom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`poison_has_symptom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`poison_has_symptom` (
  `poison_id` INT NOT NULL,
  `symptom_id` INT NOT NULL,
  PRIMARY KEY (`poison_id`, `symptom_id`),
  INDEX `fk_poison_has_symptom_symptom1_idx` (`symptom_id` ASC) VISIBLE,
  INDEX `fk_poison_has_symptom_poison1_idx` (`poison_id` ASC) VISIBLE,
  CONSTRAINT `fk_poison_has_symptom_poison1`
    FOREIGN KEY (`poison_id`)
    REFERENCES `mydb`.`poison` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poison_has_symptom_symptom1`
    FOREIGN KEY (`symptom_id`)
    REFERENCES `mydb`.`symptom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`symptom_has_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`symptom_has_ingredient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`symptom_has_ingredient` (
  `symptom_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  PRIMARY KEY (`symptom_id`, `ingredient_id`),
  INDEX `fk_symptom_has_ingredient_ingredient1_idx` (`ingredient_id` ASC) VISIBLE,
  INDEX `fk_symptom_has_ingredient_symptom1_idx` (`symptom_id` ASC) VISIBLE,
  CONSTRAINT `fk_symptom_has_ingredient_symptom1`
    FOREIGN KEY (`symptom_id`)
    REFERENCES `mydb`.`symptom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_symptom_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `mydb`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`poison_has_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`poison_has_ingredient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`poison_has_ingredient` (
  `poison_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  PRIMARY KEY (`poison_id`, `ingredient_id`),
  INDEX `fk_poison_has_ingredient_ingredient1_idx` (`ingredient_id` ASC) VISIBLE,
  INDEX `fk_poison_has_ingredient_poison1_idx` (`poison_id` ASC) VISIBLE,
  CONSTRAINT `fk_poison_has_ingredient_poison1`
    FOREIGN KEY (`poison_id`)
    REFERENCES `mydb`.`poison` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poison_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `mydb`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
